### ISSUE TITLE
API en heroku - sugerencia

### ISSUE THREAD

**Issue by erm3nda** [inigoflores/ds-codigos-postales-ine-es#1]
Andaba pensando, ya que he visto esto en otros sitios, si no podrías tal vez subir el trabajo a heroku (o similar) y así tener una API pública para todos.

Tenía pensado hacer todo esto en Python usando otras bases de datos, hasta que me he cruzado con tu trabajo. Tal vez te interese dar tú mismo el proyecto de alta con tu actual código PHP y "que sume en tu repo".

Por lo demás, gracias, no sabía que ine tenía todos estos datos. (Es gracioso saber que Correos -organismo oficial- vende este tipo de información). Ya me he bajado algunas otras bases de datos estáticas de otras fuentes para contrastar de forma múltiple.

Ya cuando tenga un rato tengo pensado hacer un modulo Python que haga mas o menos lo mismo que tienes tu montado aquí.

Saludos!

**Comment by otundra** [comment]
@erm3nda lo hiciste al final?

**Comment by erm3nda** [comment]
Sinceramente no me ha hecho falta :-( tal vez debí ahorrarme el comentario.
