### ISSUE TITLE
No acaba de funcionar

### ISSUE THREAD

**Issue by didacrios** [inigoflores/ds-codigos-postales-ine-es#2]
Gracias por el script, he localizado un par de incidencias que he solucionado en local, si tengo tiempo de arreglarlo voy a hacer una PR

Lo primero es que al extraer el zip busca un fichero que contenga "TRAM" y luego lo lee, pero ese fichero es otro zip así que hay que volverlo a descomprimir.

Y luego al agrupar se hace con el código de municipio, pero puede ser que haya varios municipios con el mismo código postal y de municipio, así que habría que agrupar de otra forma, sinó se pierden datos.

Así de primeras se me ocurre agrupar por el nombre del municipio

```php
$output[$nombre_entidad_singular] = compact('codigo_postal','municipio_id','nombre_entidad_singular');
```

**Comment by inigoflores** [comment]
Hola @didacrios 

Gracias por tus comentarios.

El script no se ha actualizado en algún tiempo, y el proveedor ha debido de cambiar la estructura de los ficheros. Si quieres hacer un PR, estaré encantado de revisarlo y hacer un merge si es correcto.

Con respecto a lo que comentas acerca de como se agrupa, creo que estás en un error. Los campos `municipio_id` y `código_postal` tienen una relación N:N, por lo que no se debe agrupar si no queremos perder información. De hecho, el script hace lo siguiente:

    $output[$codigo_postal][$municipio_id] = compact('codigo_postal','municipio_id','nombre_entidad_singular');

Se trata de un array multidimensional donde se preserva tanto el `$codigo_postal` como `$municipio_id`. No se hace agrupación ninguna.

**Comment by didacrios** [comment]
Sí, el problema era mas para mi caso de uso, porque quiero obtener los municipios, y los códigos postales, en el caso que te comentaba, si varios municipios tienen el mismo código postal y mismo codigo de municpio, los datos que se generan seran incorrectos, esto pasa por ejemplo, con lineas como estas:

```
4314401001   00017010000600000            4376500000S0000S   20181231 01001   0001701                         ARGILAGA (L')            ARGILAGA (L')            00006SANT ROC                 00000                                                              4376500000S0000S
4314401001   00043010000400000            4376520002 9998    20181231 01001   0004301                         SECUITA (LA)             SECUITA (LA)             00004PROGRES                  00000                                                              4376520002 9998 
4314401001   00056010004200000            4376520002 9998    20181231 01001   0005601                         VISTABELLA               VISTABELLA               00042SANT BARTOMEU            00000                                                              4376520002 9998 
```

Como ves tienen el mismo código postal, y código de municipio, pero al agrupar por ellos, se va quedar solo con el ultimo que lea en el while, en este caso "Vistabella" como referencia de municipio para el código postal 43765

**Comment by inigoflores** [comment]
Creo que puedes estar confundiendo _municipios_ con _entidades singulares_ (pueblo, barrío, etc. diferenciado dentro de un municipio).

En los archivos fuente no se proporciona el nombre de los municipios, pero sí la entidad singular, así como la calle. La agrupación que se ha hecho ha sido para que la pareja `codigo_postal , municipio_id` sea única, perdiéndose información en caso de entidades singulares duplicadas.

En el caso que comentas, todos esos registros se han reducido a la pareja `43765, 43144`.
