### ISSUE TITLE
Provincias

### ISSUE THREAD

**Issue by otundra** [inigoflores/ds-codigos-postales-ine-es#4]
Hola! Sería sencillo meter las provincias al listado [codigos_postales_municipios_join.csv](https://github.com/inigoflores/ds-codigos-postales-ine-es/blob/master/data/codigos_postales_municipios_join.csv)?

Un saludo y gracias!

**Comment by inigoflores** [comment]
Hola rrrraul

Siento el retraso en contestarte, no me había llegado la notificación.

Supongo que ya no lo necesitas, pero te pongo la solución en cualquier caso:

```
$ wget https://raw.githubusercontent.com/codeforspain/ds-organizacion-administrativa/master/data/provincias.csv 
$ csvsql --query "SELECT CAST(codigo_postal as INTEGER),CAST(municipio_id as INTEGER),municipio_nombre,substr(municipio_id,1,2) as CPRO  FROM codigos_postales_municipios" ds-codigos-postales-ine-es/data/codigos_postales_municipios.csv \
    | csvjoin -c "CPRO,provincia_id" - provincias.csv 
    > codigos_postales_municipios_provincias.csv 
```

Un saludo

**Comment by otundra** [comment]
Gracias Iñigo!

Raúl

—
659 509 062
lapatineta.com

**Comment by jusjjusj** [comment]
En primer lugar dar las gracias por el trabajo que compartis para todos porque es de gran ayuda.
Yo quiero contribuir en la medida de mis conocimientos con esta pequeña adaptación a la solución aportada anteriormente para generar un CSV que contenga 3 columnas (codigo_postal, municipio, nombre) 

codigo_postal -> codigo_postal de una localidad
municipio -> nombre de la localidad
nombre -> nombre de la provincia de la localidad

$ wget https://raw.githubusercontent.com/codeforspain/ds-organizacion-administrativa/master/data/municipios.csv -O ../data/municipios.csv

$ csvsql -I --query "SELECT municipio_id,nombre as municipio FROM municipios" ../data/municipios.csv | csvjoin -I -c "municipio_id" - ../data/codigos_postales_municipiosid.csv | csvcut -c "codigo_postal,municipio_id,municipio" > ../data/codigos_postales_municipios.csv

$ wget https://raw.githubusercontent.com/codeforspain/ds-organizacion-administrativa/master/data/provincias.csv -O ../data/provincias.csv

$ csvsql -I --query "SELECT codigo_postal,municipio,substr(municipio_id,1,2) as provincia_id FROM codigos_postales_municipios order by codigo_postal" ../data/codigos_postales_municipios.csv | csvjoin -I -c "provincia_id" - ../data/provincias.csv | csvcut -c "codigo_postal,municipio,nombre"  > ../data/codigos_postales_municipios_provincias.csv


Con el fichero codigos_postales_municipios_provincias.csv podemos validar los campos de localidad y provincia a partir de un código postal para cualquier formulario de registro.

Subo el fichero actualizado de municipios por provincia última actualización: 17 de junio de 2021
[municipios.csv](https://github.com/inigoflores/ds-codigos-postales-ine-es/files/7212945/municipios.csv)


basándome en https://www.ine.es/daco/daco42/codmun/diccionario21.xlsx

y el fichero final que he obtenido 
[codigos_postales_municipios_provincias.csv](https://github.com/inigoflores/ds-codigos-postales-ine-es/files/7212943/codigos_postales_municipios_provincias.csv)
