### ISSUE TITLE
¿hay alguna documentación para entender el script?

### ISSUE THREAD

**Issue by SanchezBelen** [inigoflores/ds-codigos-postales-ine-es#6]
Acabo de registrarme en GIT solo para preguntar sobre este script

He intentado ejecutarlo sin modificar nada en mi servidor, pero me da error.
Con PHP 7.4:
sizeof(): Parameter must be an array or an object that implements Countable in ...... line 19

Con PHP 8.0: 
Warning: Undefined variable $argv in .... script.php on line 19
Fatal error: Uncaught TypeError: sizeof(): Argument #1 ($var) must be of type Countable|array, null given in

Quizas el proposito de este repositorio no sea el descargar subirlo y que funcione, no comprendo bien GIT

Intento solucionar algunas cosas que no me gustan en un CSV (codigos_postales_municipios_entidades.csv)

 a) municipio_nombre, me gustaria que se formara igual que se forma entidad_singular_nombre y nucleo_nombre
Actualmente: (lo ideal seria que fueran iguales, a mi me gusta entre parentesis, pero me da igual)
municipio_nombre: Pobla de Massaluca, La
entidad_singular_nombre: Pobla de Massaluca (La)

 b) nucleo_id, resultaria interesante tener tambien el ID del nucleo (por el punto C)

 c) numero de habitantes, el INE tiene el numero de habitantes por unidad poblacional que entiendo es el nucleo.
https://www.ine.es/nomen2/ficheros.do
Me gustaria añadir a la base de datos el total de poblacion, dato super interesante.

 d) Si consiguiera añadir latitud y longitud seria ideal pero no veo que este dato este en el INE 

Por lo tanto, mi CSV preferido seria tal como asi:
CodigoPostal : IDprovincia : IDmunicipio : IDnucleo : Municipio : Entidad_Singular : Nucleo

si alguien pudiera iluminarme con esto, me ayudaria muchisimo :)

**Comment by inigoflores** [comment]
Hola @SanchezBelen 

Siento el retraso en contestarte.

¿Puede ser que hayas ejecutado el script desde el navegador y no desde la línea de comandos? El error que esta dando puede indicar esto.

Con respecto a las distintas cuestiones que planteas, te contesto:

> a) municipio_nombre, me gustaria que se formara igual que se forma entidad_singular_nombre y nucleo_nombre
> Actualmente: (lo ideal seria que fueran iguales, a mi me gusta entre parentesis, pero me da igual)
> municipio_nombre: Pobla de Massaluca, La
> entidad_singular_nombre: Pobla de Massaluca (La)

El objetivo de este proyecto es recoger los datos de la fuente del INE de la forma más fidedigna posible. Las transformaciones que comentas supondrían alterar la fuente. Lo que se puede hacer es utilizar este dataset como base para otro donde haces las modificaciones que te interesen. Lo más fácil es seguramente crear un script para trabajar directamente sobre los datos ya extraídos del INE.

> b) nucleo_id, resultaria interesante tener tambien el ID del nucleo (por el punto C)

El id del núcleo poblacional está ya incluido. En la fuente tiene una longitud de 7 dígitos, a los que se le suman los 5 del código del municipio, para hacer un total de 12. 

![image](https://user-images.githubusercontent.com/5518087/104137131-f2e38c80-539a-11eb-9101-6809fc316007.png)

* [Diseño de Registro Callejero Censo Electoral](https://www.ine.es/ss/Satellite?blobcol=urldata&blobheader=application%2Fmsword&blobheadername1=Content-Disposition&blobheadervalue1=attachment%3B+filename%3Ddisenocallejero.doc&blobkey=urldata&blobtable=MungoBlobs&blobwhere=817%2F26%2Fdisenocallejero%2C1.doc&ssbinary=true)

El problema que veo es que en el conjunto de datos de población que mencionas, el código de unidad poblacional solo tienen 6 dígitos. Según el [Diseño de Registro de Unidades Poblaciones](https://www.ine.es/nomen_files/DisenioRegistro.xls) (.xls), 6 dígitos es lo que tiene el código de unidad poblacional.

Parece ser que se puede establecer algún tipo de relación entre uno y otro. Creo que omitiendo el antepenúltimo dígito, obtienes una correspondencia exacta con el código de unidad poblacional de la otra fuente.

Un ejemplo. Del Excel de población:

28 | 015 | 000101 ARROYOMOLINOS | 12979 | 6518 | 6461
-- | -- | -- | -- | -- | --
28 | 015 | 000199 *DISEMINADO* | 2 | 1 | 1

Del fichero codigos_postales_municipiosid_entidades.csv


|28939|28015                        |280150001701|Arroyomolinos                                |Arroyomolinos|
|-----|-----------------------------|------------|---------------------------------------------|-------------|
|28939|28015                        |280150001799|Arroyomolinos                                |*diseminado* |

En el segundo caso eliminado el 7 se obtiene una correspondencia.

> c) numero de habitantes, el INE tiene el numero de habitantes por unidad poblacional que entiendo es el nucleo.
> https://www.ine.es/nomen2/ficheros.do. Me gustaría añadir a la base de datos el total de población, dato super interesante.

Una vez hayas aclarado la relación entre los los códigos de unidad poblacional de uno y otro datasets, puedes hacer un join para incluir la población. Me temo que esto se escapa de los objetivos de este proyecto.

> d) Si consiguiera añadir latitud y longitud seria ideal pero no veo que este dato este en el INE

Efectivamente, no aparece en esta fuente del INE. Pero piensa que más que un valor de latitud y longitud, lo que necesitas son las áreas de aplicación de estos códigos postales, que en muchos casos abarcan decenas de km cuadrados.

En este dataset tienes los polígonos relacionados con cada código postal: https://github.com/inigoflores/ds-codigos-postales

Desgraciadamente no se actualiza desde hace unos cuantos años, al haber sido los datos retirados por parte de Correos.
