### ISSUE TITLE
Codigos postales

### ISSUE THREAD

**Issue by adok2** [inigoflores/ds-codigos-postales-ine-es#7]
Buenas, felicidades por el trabajo impresionante que habéis hecho de primeras.

La estoy liando con vuestros datos y  he podido observar es que le faltan bastante códigos, os pongo de ejemplo unos cuantos:
46000
28669
29071
07121
35319
29071
30353

Como podéis observar son zonas muy dispares, no se si es que el INE no los da o algo ha pasado ¿alguna idea?

**Comment by inigoflores** [comment]
Hola adok2

Me alegro de que te guste el proyecto! Aunque es cierto que faltan códigos postales. Desgraciadamente, el INE no tiene actualizadas todas las direcciones postales en el censo. Aquí nos limitamos a poner en un formato fácil de manejar la información que ahí aparece. Dependiendo de la aplicación, a lo mejor necesitas acudir a una fuente más fiable.

Saludos
